### ISSUE TITLE
iOS camera aspect ratio wrong

### ISSUE THREAD

**Issue by wesbillman** [contactlutforrahman/flutter_qr_bar_scanner#4]
I tried creating the widget in 2 ways and both show the aspect ratio wrong

```dart
// specify fit
QRBarScannerCamera(
  fit: BoxFit.cover,
  onError: (context, error) => <error code>,
  qrCodeCallback: (code) {
    _qrCallback(context, code);
  },
);

// don't specify fit
QRBarScannerCamera(
  onError: (context, error) => <error code>,
  qrCodeCallback: (code) {
    _qrCallback(context, code);
  },
);
```

Both approaches result in the same output format on the iOS camera:
![IMG_0427](https://user-images.githubusercontent.com/51647/75174336-a2fdc780-56ed-11ea-973a-7a23c991bb4f.PNG)

**Comment by JulioLongo** [comment]
Same Here

**Comment by danilomna** [comment]
same here, odd.

**Comment by troyanskiy** [comment]
same iPhone 6s

**Comment by troyanskiy** [comment]
Here is fix on PR.
Others can test it as well by adding (replacing) depedencies by
```
flutter_qr_bar_scanner:
    git:
      url: https://github.com/troyanskiy/flutter_qr_bar_scanner.git
      ref: master
```
